### ISSUE TITLE
[Feature Request]: Use a php matrix instead of single php version for coding standards

### ISSUE THREAD

**Issue by luislard** [inpsyde/reusable-workflows#15]
### Is your feature request related to a problem?

Currently the coding standards check can happen only with one PHP version, this is a problem when you want to use this reusable workflow and run the coding standards under several PHP versions.
I am referring to: https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/coding-standards-php.yml#L44

### Describe the desired solution

It would be great to add the strategy matrix to have this working:
See:
```
jobs:
  static-code-analysis-backend:
    name: Static code analysis PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "7.4","8.0","8.1" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer:v2,cs2pr
      - name: Packagist.com Auth
        run: composer config --global --auth http-basic.repo.packagist.com token ${{ secrets.PACKAGIST_TOKEN }}
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Install composer dependencies (use cache)
        uses: ramsey/composer-install@v1
        with:
          composer-options: "--prefer-dist"
      - name: Check coding standards PHP
        run: vendor/bin/phpcs --report-full --report-checkstyle=./phpcs-report.xml
      - name: Check Psalm
        run: vendor/bin/psalm --output-format=github --php-version=${{ matrix.php-versions }}
      - name: Annotate coding standards errors PHP
        if: always()
        run: cs2pr --graceful-warnings ./phpcs-report.xml
```

### Describe the alternatives that you have considered

Add the matrix strategy

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
