### ISSUE TITLE
[Feature Request]: Customizable Composer Version

### ISSUE THREAD

**Issue by yeremi** [inpsyde/reusable-workflows#166]
### Is your feature request related to a problem?

When using `static-analysis-php.yml` or `tests-unit-php.yml` in a project with PHP 7.4 and Composer v1, there isn't currently an option to customize the Composer version. In this [commit](https://github.com/inpsyde/reusable-workflows/commit/b0f432f99ac5d75865214808ce883b716a56b4a1) and in this [commit](https://github.com/inpsyde/reusable-workflows/commit/8510de99748c9ac7886ac36a8cf3d6b0839d6686), the version was manually set. Additionally, it lacks the flexibility to customize the tools used, such as in the [tools: composer, cs2pr](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/static-analysis-php.yml#L54) node.

### Describe the desired solution

To experiment with different Composer versions, it would be helpful to introduce some new inputs. For example:

**static-analysis-php.yml**:
```yaml
# static-analysis-php.yml
on:
  workflow_call:
inputs:
    ...
    COMPOSER_INSTALL_VERSION:
      description: Ramsey Composer version with which the static code analysis is to be executed.
      default: ramsey/composer-install@v3
      required: false
      type: string
    
    TOOLS:
      description: Tools which the static code analysis is to be executed.
      default: composer, cs2pr
      required: false
      type: string

jobs:
  static-analysis-php:
    ...
    steps:
      ...
       - name: Set up PHP
         uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          tools: ${{ inputs.TOOLS }}  #use the default
          coverage: none
      ...
      - name: Install Composer dependencies
        uses: ${{ inputs.COMPOSER_INSTALL_VERSION }} #use the default
        with:
           composer-options: ${{ inputs.COMPOSER_ARGS }}
   ...
```
These could be used in a file like **my-custom-static-analysis-php.yml**:

```yaml
# custom-static-analysis-php.yml
jobs:
  ...
  static-code-analysis-php:
     uses: inpsyde/reusable-workflows/.github/workflows/static-analysis-php.yml@main
     strategy:
        matrix:
          php: [ "7.4" ]
     secrets:
         COMPOSER_AUTH_JSON: ${{secrets.PACKAGIST_AUTH_JSON}}
     with:
         PHP_VERSION: ${{ matrix.php }}
         # my custom tools with composer:v1
         tools: composer:v1, cs2pr
     # my custom composer-install version
     uses: ramsey/composer-install@v1
    ...
```

This could be beneficial in cases where specific projects require a particular version for compatibility reasons.

### Describe the alternatives that you have considered

Defining the input as it's currently being used ensures compatibility with the packages that rely on these workflows.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by Chrico** [comment]
Actually the `ramsey/composer-install@v3` does not indicate that version 3 of composer is being used. It is just the version 3 of the action, not of composer itself. To select the version of composer you need to install it through the `shivammathur/setup-php@v2`-action:

```yml
- name: Setup PHP with composer version 2
  uses: shivammathur/setup-php@v2
  with:
    php-version: '8.3'
    tools: composer:v2 # or "composer:v1", "composer:snapshot", "composer:preview"
```

See tools list here: 
https://github.com/shivammathur/setup-php?tab=readme-ov-file#wrench-tools-support

After checking the code of `shivammathur/setup-php`, it seems like the composer version is picked based on the PHP version - see test data here: https://github.com/shivammathur/setup-php/blob/9f51892bda551c29f469a2b3d8514b6d2ed84dc9/__tests__/tools.test.ts#L320-L341 :

```shell
> php composer-7.4-stable.phar -V
Composer version 2.8.1 2024-10-04 11:31:01
```

---

The `PHP_TOOLS` would need to be used in all PHP-related reusable workflows which use the `shivammathur/setup-php`-action:

- [lint-php.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/lint-php.yml#L56)
- [static-analysis-php.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/static-analysis-php.yml#L51)
- [coding-standards-php.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/coding-standards-php.yml#L56)
- [build-plugin-archive.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/build-plugin-archive.yml#L113)
- [build-assets-compilation.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/build-assets-compilation.yml#L127)
- [build-and-push-assets.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/build-and-push-assets.yml#L267)
- [tests-unit-php.yml](https://github.com/inpsyde/reusable-workflows/blob/c55a8ba06a74a7065e06f6b8a246e15ec613ff92/.github/workflows/tests-unit-php.yml#L51)

We already had a few internal discussions and the main problem is that we sometimes cannot just simply allow to overwrite the complete `PHP_TOOLS` list due some required tools, while some tools are always installed by default (like composer) if not part of the list. 

I would to suggest that we quickly align internally about this topic and how we can generalize this for all PHP-related reusable-workflows. 👍🏻 CC @tyrann0us
