### ISSUE TITLE
[Feature Request]: Review reusable-workflows and "env"-usage

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#176]
We need to review all reusable workflows and what they write into `env:`. GitHub Actions can have access to the env-variables, so we only should write the required information (like the `NODE_TOKEN`) into the `env:`-section.

---

[_lint-docs.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/_lint-docs.yml)

✅  nothing

---

[automatic-release.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/automatic-release.yml)

```yml
      HAS_CONFIG: false
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
      GITHUB_USER_SSH_PUBLIC_KEY: ${{ secrets.GITHUB_USER_SSH_PUBLIC_KEY }}
```

---

[build-and-push-assets.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-and-push-assets.yml)

```yml
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NODE_CACHE_MODE: ''
      GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
      GITHUB_USER_SSH_PUBLIC_KEY: ${{ secrets.GITHUB_USER_SSH_PUBLIC_KEY }}
      COMPILE_SCRIPT: ''
      TAG_NAME: ''                                     # we'll override if the push is for tag
      TAG_BRANCH_NAME: ''                              # we'll override if the push is for tag
      NO_CHANGES: ''                                   # we'll override if no changes to commit
```

---

[build-assets-compilation.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-assets-compilation.yml)

```yml
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NODE_CACHE_MODE: ''
      GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
```

---

[build-plugin-archive.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/build-plugin-archive.yml)

```yml
      ENV_VARS: ${{ secrets.ENV_VARS }}
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
      COMPOSER_MIRROR_PATH_REPOS: 1
```

---

[coding-standards-php.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/coding-standards-php.yml)

```yml
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
```

---

[ddev-playwright.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/ddev-playwright.yml)

```yml
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NGROK: ${{ secrets.NGROK_AUTH_TOKEN != '' }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
```

---

[lint-php.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/lint-php.yml)

```yml
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
```

---

[lint-workflows.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/lint-workflows.yml)

✅ nothing

---

[static-analysis-js.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/static-analysis-js.yml)

```yml
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NODE_CACHE_MODE: ''
      GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
```

---

[static-analysis-php.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/static-analysis-php.yml)

```yml
     COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
```

---

[tests-unit-js.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/tests-unit-js.yml)

```yml
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NODE_CACHE_MODE: ''
      GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
```

---

[tests-unit-php.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/tests-unit-php.yml)

```yml
    COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
```
---

[wp-scripts-lint.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/wp-scripts-lint.yml)

```yml
      NODE_OPTIONS: ${{ inputs.NODE_OPTIONS }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
      NODE_CACHE_MODE: ''
      GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
      GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
      GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dottxado** [comment]
I already tested moving some secrets to the steps' environments during #177 

---

👉 `GITHUB_USER_SSH_KEY`

Example:
```yml
      - name: Set up SSH
        env:
          GITHUB_USER_SSH_KEY: ${{ secrets.GITHUB_USER_SSH_KEY }}
        if: ${{ env.GITHUB_USER_SSH_KEY != '' }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ env.GITHUB_USER_SSH_KEY }}
```

---

👉 `GITHUB_USER_EMAIL`
👉  `GITHUB_USER_NAME`

Example:
```yml
      - name: Set up Git
        env:
          GITHUB_USER_EMAIL: ${{ secrets.GITHUB_USER_EMAIL }}
          GITHUB_USER_NAME: ${{ secrets.GITHUB_USER_NAME }}
        if: ${{ env.GITHUB_USER_EMAIL != '' && env.GITHUB_USER_NAME != '' }}
        run: |
          git config --global user.email "${{ env.GITHUB_USER_EMAIL }}"
          git config --global user.name "${{ env.GITHUB_USER_NAME }}"
```

---

👉 `COMPOSER_AUTH_JSON`

Example:
```yml
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        env:
          COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
        with:
          php-version: ${{ inputs.PHP_VERSION }}
          tools: composer
          coverage: none
```

---

👉 `NPM_REGISTRY_TOKEN`

Example:
```yml
      - name: Set up node
        uses: actions/setup-node@v4
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_REGISTRY_TOKEN }}
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          registry-url: ${{ inputs.NPM_REGISTRY_DOMAIN }}
          cache: 'npm'
```
