### ISSUE TITLE
[Feature Request]: New reusable workflow "compatibility check PHP"

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#18]
### Is your feature request related to a problem?

We had now several discussions internally about:

> "How to check if PHP code is compatible with PHP Version x.y".

### Describe the desired solution

The decision internally was to introduce a new workflow `compat-check-php.yml`. This workflow will look like the following:

```yml
name: Compatibility check PHP

on:
  workflow_call:
    inputs:
      PHP_MATRIX:
        description: Matrix of PHP versions as a JSON formatted object.
        default: '["7.4"]'
        required: false
        type: string
      COMPOSER_ARGS:
        description: Set of arguments passed to Composer.
        default: '--prefer-dist'
        required: false
        type: string
    secrets:
      COMPOSER_AUTH_JSON:
        description: Authentication for privately hosted packages and repositories as a JSON formatted object.
        required: false
      ENV_VARS:
        description: Additional environment variables as a JSON formatted object.
        required: false

jobs:
  compatibility-check-php:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ${{ fromJson(inputs.PHP_MATRIX) }}
    env:
      COMPOSER_AUTH: '${{ secrets.COMPOSER_AUTH_JSON }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Set up custom environment variables
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        if: ${{ env.ENV_VARS }}
        uses: actions/github-script@v6
        with:
          script: |
            JSON
              .parse(process.env.ENV_VARS)
              .forEach(envVar => core.exportVariable(envVar.name, envVar.value));

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1
        with:
          composer-options: ${{ inputs.COMPOSER_ARGS }}

      - name: Run PHP compat check
        run: find ./src/ ./inc/ ./tests/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

```

----

### Open Topics

- Which configuration is required (paths?)
- Should we install composer dependencies and check compat there as well?
- Documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AlexP11223** [comment]
> * Which configuration is required (paths?)

Should not be needed if done like in my PR, simply check all files repo before running Composer.

```
find . -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l
```

**Comment by gmazzap** [comment]
I remeber whenwe enabled thsi on a website repo, even not touching vendors such code required 20+ seconds to run.
If you multiply by several PHP versions, that is a bunch of time.

So selecting paths might be a matter of saving time, more than anything else.

As I proposed other places, why not using [PHP-Parallel-Lint](https://github.com/php-parallel-lint/PHP-Parallel-Lint)?

That tool is even provided by the ["Setup PHP" action](https://github.com/shivammathur/setup-php#wrench-tools-support)

Tha means this workflow could be (only relevant parts):

```yaml
on:
  workflow_call:
    inputs:
      LINT_ARGS:
        description: Set of arguments passed to PHP-Parallel-Lint.
        default: '-e php --colors --show-deprecated'
        required: false
        type: string

jobs:
  compatibility-check-php:
    steps:

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          tools: parallel-lint

      - name: Run PHP compat check
        run: parallel-lint ${{ inputs.LINT_ARGS }}
```

This will save potentially a _lot_ of time:

- There's *no* Composer installation. The "Install Composer dependencies" can be skipped entirely. Parallel Lint is installed as binary to PHP via "setup-php" action
- The tool processes files in parallel, so there could an speed increase of 3x/4x
- Thanks to the fact one can pass params to `parallel-lint` comman, one could pass `--exclude` for paths containing files not used in production

Besides saving time, the action provides also more flexibility:

- Possibility to get checkstyle formatting (and thus GitHub annotation via [CS2PR](https://github.com/staabm/annotate-pull-request-from-checkstyle#using-php-parallel-lint))
- Possibility to show deprecations
