### ISSUE TITLE
[Feature Request]: tests-unit-php.yml does not support codecov

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#188]
### Is your feature request related to a problem?

We should add to https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/tests-unit-php.yml support for Codecov. 

### Describe the desired solution

The additional step could be like:

```yaml
            -   name: Coverage
                if: ${{ hashFile('coverage.xml') == '' }}
                uses: codecov/codecov-action@v4
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    files: ./coverage.xml
                    flags: unittests
                    verbose: true
```

### Describe the alternatives that you have considered

-

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
