### ISSUE TITLE
[Feature Request]: New workflow "WP-Scripts QA"

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#46]
### Is your feature request related to a problem?

We should create a new reusable workflow "static-wp-scripts-qa.yml" which contains following:

- Lint Markdown: `wp-scripts lint-md-docs docs/**/*.md`
- Lint Scripts: `wp-scripts lint-js resources/{ts,js}/**/*{js,ts,tsx}`
- Lint Styles `wp-scripts lint-style resources/{css,scss}/**/*.{css,scss}`

Following inputs are required:
```yaml
      NPM_REGISTRY_DOMAIN:
        description: Domain of the private npm registry.
        default: https://npm.pkg.github.com/
        required: false
        type: string
      NODE_VERSION:
        description: Node version with which the static code analysis is to be executed.
        default: 16
        required: false
        type: string
      ESLINT_ARGS:
        description: Set of arguments passed to ESLint.
        default: '-o eslint_report.json -f json --ext .js,.jsx,.ts,.tsx ./resources'
        required: false
        type: string
      PACKAGE_MANAGER:
        description: Package manager with which the dependencies should be installed (`npm` or `yarn`).
        default: 'yarn'
        required: false
        type: string
      NODE_OPTIONS:
        description: Space-separated list of command-line Node options.
        type: string
        default: ''
        required: false
```

Following secrets are required:

```yml
      NPM_REGISTRY_TOKEN:
        description: Authentication for the private npm registry.
        required: false
```

---

Additionally we should update following reusable-workflows and add a notice (to be defined) to point to the new workflow:

- [static-analysis-sass.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/static-analysis-sass.yml)
- [static-analysis-js.yml](https://github.com/inpsyde/reusable-workflows/blob/main/.github/workflows/static-analysis-js.yml)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
