### ISSUE TITLE
[Feature Request]: Allow injection ENV_VARS as "secrets" in all workflows

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#51]
### Is your feature request related to a problem?

Right now only in the tests-unit-php.yml workflow it is possible to inject `ENV_VARS` via `secrets`.

### Describe the desired solution

We should add the `ENV_VARS` as `secrets` to all workflows we have right now:

- build-and-push-assets.yml
- build-assets-compilation.yml
- build-plugin-archive.yml
- coding-standards-php.yml
- lint-php.yml
- static-analysis-js.yml
- static-analysis-php.yml
- static-analysis-sass.yml
- tests-unit-js.yml
- tests-unit-php.yml
- wp-scripts-lint.yml

parsing and adding them to the env is done by following step:

```yaml
 - name: Set up custom environment variables
        env:
          ENV_VARS: ${{ secrets.ENV_VARS }}
        if: ${{ env.ENV_VARS }}
        uses: actions/github-script@v6
        with:
          script: |
            JSON
              .parse(process.env.ENV_VARS)
              .forEach(envVar => core.exportVariable(envVar.name, envVar.value));
```

### Describe the alternatives that you have considered

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
