### ISSUE TITLE
[Feature Request]: Change matrix usage via JSON-string

### ISSUE THREAD

**Issue by Chrico** [inpsyde/reusable-workflows#58]
### Is your feature request related to a problem?

Right now we have `test-unit-php.yml` and `lint-php.yml` which allow `on.workflow_call_inputs.PHP_MATRIX` to be set. This JSON string will be used internally to run the reusable workflow against multiple PHP_VERSIONS.

It seems that since 08/2022 Github supports matrix usage when using reusable-workflows https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-a-matrix-strategy-with-a-reusable-workflow . So instead of adding `PHP_MATRIX` as a JSON-string we should convert those to `on.workflow_call_inputs.PHP_VERSION` and the matrix has to be defined outside in the calling workflow.

**⚠️ This could be a breaking change if we decide to remove the "PHP_MATRIX" input.**

**before:**
```yaml
name: Unit tests PHP
on:
  pull_request:
jobs:
  tests-unit-php:
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
      ENV_VARS: >-
        [{"name":"EXAMPLE_USERNAME", "value":"${{ secrets.USERNAME }}"}]
    with:
      PHP_MATRIX: >-
        ["8.0", "8.1"]
```

**after**
```yaml
name: Unit tests PHP
on:
  pull_request:
jobs:
  tests-unit-php:
    strategy:
      matrix:
        php: ["8.0", "8.1"]
    uses: inpsyde/reusable-workflows/.github/workflows/tests-unit-php.yml@main
    secrets:
      COMPOSER_AUTH_JSON: ${{ secrets.COMPOSER_AUTH_JSON }}
      ENV_VARS: >-
        [{"name":"EXAMPLE_USERNAME", "value":"${{ secrets.USERNAME }}"}]
    with:
      PHP_VERSION: ${{ matrix.php }}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
