### ISSUE TITLE
[Feature Request]: Disable coverage where applicable

### ISSUE THREAD

**Issue by tyrann0us** [inpsyde/reusable-workflows#7]
### Is your feature request related to a problem?

Xdebug is enabled by default on Ubuntu GitHub Actions images. However, we don't use it in any of the PHP-related workflows. Since it has a negative impact on PHP performance, it should be disabled.

### Describe the desired solution

Add `coverage: none` to the "Set up PHP" step as described here: https://github.com/shivammathur/setup-php#disable-coverage:
```yaml
- name: Set up PHP
  uses: shivammathur/setup-php@v2
  with:
    # […]
    coverage: none
```

### Describe the alternatives that you have considered

It is unclear what the actual performance benefit would be, so the alternative is not to add this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
